services:
  redis:
    image: redis:7.2
    container_name: conx-redis

    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

    ports:
      - "127.0.0.1:6379:6379"

    restart: unless-stopped