server:
  address: 0.0.0.0

spring:
  application:
    name: conx-server

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  data:
    redis:
      host: redis
      port: 6379

google:
  user: ${GOOGLE_USER}
  password: ${GOOGLE_PASSWORD}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

logging:
  level:
    root: INFO
    com.example.logdemo: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
        exclude: env, heapdump, threaddump, configprops, quartz

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true