server:
  address: 0.0.0.0

spring:
  application:
    name: conx-server

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}